### ISSUE TITLE
Transparent Background not working

### ISSUE THREAD

**Issue by Skyyblaze** [riyasy/FlyPhotos#1]
The transparent background feature doesn't seem to work for me as can be seen here:

![grafik](https://github.com/riyasy/FlyPhotos/assets/22203339/0b0a81f6-fe8a-4c4b-9f25-5b2830210a3c)

My system:

Windows 11 23H2 22631.2361
GPU: Geforce RTX 4070

Wallpaper handled by Wallpaper Engine if that influences anything.

**Comment by riyasy** [comment]
Can you give the link of Wallpaper engine software?
If possible also, can you check without the wallpaper engine software?

**Comment by Skyyblaze** [comment]
It wasn't the fault of Wallpaper Engine, testing revealed it was caused by MicaForEveryone: https://github.com/MicaForEveryone/MicaForEveryone

I excluded Fly from MFE now and it works properly! :)

**Comment by riyasy** [comment]
Also Picasa photo viewer transparency is faked. Means it takes a screenshot during startup and displays it full screen and the photo over it. It makes everything easier and gives superior performance. We can check this by playing a video and then launching picasa veiwer and then video freezes while audio plays.
I have implemented that version also with Fly also but went with real transparency in the release. May be in a future release, I will add fake transparency as an option since it improves performance vastly while panning and zooming especially in older PCs.

**Comment by Skyyblaze** [comment]
Interesting, thanks for the explanation! And yeah a option for fake-transparency might be great for low-powered machines. Honestly when/if you implement animations like Picasa has Fly will be the perfect, modern replacement! Also is animated .gif playback planned?
