### ISSUE TITLE
Not working : shows only one photo if executed from other than Explorer

### ISSUE THREAD

**Issue by slet-mig** [riyasy/FlyPhotos#11]
FlyPhoto set as default app for JPEG.

Double clicking in Explorer - Right-Left arrow on keyboard shuffles between photos.

Double clicking form other programs f.x. TotalCommander, only show the one photo.  Not possible to use Right-Left arrow.  Program doesn't detect other photos in that folder.

**Comment by ccrowles** [comment]
Same issue here but when opening it within [Files](https://github.com/files-community/Files) (an alternative to Windows Explorer).

![Screenshot_2024-08-22_10-25-30_860](https://github.com/user-attachments/assets/0d3b2870-254e-4d7a-bb7d-284a23911549)

**Comment by riyasy** [comment]
One of the primary requirements while coding Flyphotos was to interact with the file explorer shell and get the sorted and filtered file list as seen exactly in file explorer and show the files in the same order as in file explorer.
I understand that Fly photos can be launched from other applications if we set it as the default app. 
In the next version, I shall change such that if the interaction with file explorer fails, will list the other files in the same folder using normal file and folder APIs.

**Comment by ccrowles** [comment]
Sorry for my ignorance, but what would that mean?
(To clarify: I know what an API is, I don't know what a "normal" file and folder api is/what it will happen with the sort order when using it)

**Comment by riyasy** [comment]
I meant in most programming languages, we can list files inside a folder if we have a path.  
But FlyPhotos was not coded like that. In FIle explorer, people may change sort order may filter such that only some files are visible. In that case we need to respect the sort and filter operations done in File explorer. So rather than listing all files in a folder, Flyphotos uses interaction with windows shell to get list of files which are shown in current File explorer window.

Now I have modified it such that in case this shell interaction approach fails, I shall blindly list all files in that folder for navigation using left right arrow.

Please check the latest version.

**Comment by ccrowles** [comment]
Works perfectly, thank you!

**Comment by ccrowles** [comment]
Works perfectly, but unfortunately lists them in a different order (which I'm guessing is now name order) I'm guessing due to the normal file & folders API that you mentioned. Unfortunately this makes using FlyPhotos quite confusing to use for me, because most of my folders are listed by date created, so if it lists all the images by name it becomes extremely confusing to scroll images.

Is there no way for FlyPhotos to still follow the Windows Explorer sort order, even when opened by another software?

**Comment by riyasy** [comment]
I understand the pain. But unfortunately, We won't be able to get the sort order from a third party tool. You can check with Windows photos also. One option would be to give the sort order as a setting in a future version.

**Comment by ccrowles** [comment]
I understand, thank you for your help!
An option to give the sort order as a setting in the future would be lovely, if possible.

**Comment by Skyyblaze** [comment]
I'm having a similar issue when using the Tabbed File Explorer in Windows 11:

1: Open a folder with images

2: Open a new tab in explorer with a folder also with images

3: Open a image with Fly in the second tab

In that scenario Fly will open the image normally but when go through pictures in Fly it will list all pictures from the folder in Tab 1, not Tab 2.

**Comment by riyasy** [comment]
> I'm having a similar issue when using the Tabbed File Explorer in Windows 11:
> 
> 1: Open a folder with images
> 
> 2: Open a new tab in explorer with a folder also with images
> 
> 3: Open a image with Fly in the second tab
> 
> In that scenario Fly will open the image normally but when go through pictures in Fly it will list all pictures from the folder in Tab 1, not Tab 2.

Can you open this bug as a new bug. Intuitively, I think this will be a difficult bug to fix. :-)

**Comment by riyasy** [comment]
> I'm having a similar issue when using the Tabbed File Explorer in Windows 11:
> 
> 1: Open a folder with images
> 
> 2: Open a new tab in explorer with a folder also with images
> 
> 3: Open a image with Fly in the second tab
> 
> In that scenario Fly will open the image normally but when go through pictures in Fly it will list all pictures from the folder in Tab 1, not Tab 2.

Fixed in 2.3.1

**Comment by Skyyblaze** [comment]
> > I'm having a similar issue when using the Tabbed File Explorer in Windows 11:
> > 1: Open a folder with images
> > 2: Open a new tab in explorer with a folder also with images
> > 3: Open a image with Fly in the second tab
> > In that scenario Fly will open the image normally but when go through pictures in Fly it will list all pictures from the folder in Tab 1, not Tab 2.
> 
> Fixed in 2.3.1

Sorry for not replying sooner, I can confirm it's fixed!
