### ISSUE TITLE
Suggestion: Add a right-click menu when right-clicking an image inside Fly with options like "Open in explorer", "Copy File Name" and "Copy Path"

### ISSUE THREAD

**Issue by Skyyblaze** [riyasy/FlyPhotos#9]
Would it be possible to implement a right-click menu in Fly similar to Picasa where, if you right-click the actual image in Fly you get a context menu with functions such as "Open in explorer", "Copy File Name" and "Copy Path"?

**Comment by riyasy** [comment]
It's already there in the latest version. Right click will give the same menu as windows file explorer menu.

**Comment by riyasy** [comment]
Closing as requested feature is already available.

**Comment by Skyyblaze** [comment]
Hmm then I might have a bug, I run 2.2.0 and right-clicking next to a picture makes Fly go windowed but right-clicking on the picture does nothing for me.

**Comment by riyasy** [comment]
Right clicking outside the picture will make Fly go windowed. And right clicking on the picture should yield the windows explorer right click menu itself. I have tested it only on Windows 11. 
I use Fly personally also and had noticed once it was not giving the right click menu. Could not reproduce the issue again to debug. I shall add some more logs for right click in next version and we can have a look into your issue.

**Comment by riyasy** [comment]
Right clicking outside the picture will make Fly go windowed. And right clicking on the picture should yield the explorer right click menu itself. I have tested it only on Windows 11. 
I use Fly personally also and had noticed once it was not giving the right click menu. Could not reproduce the issue again to debug. I shall add some more logs on that side in the next version and we can have a look into your issue.

Please raise as a bug so that I can keep track.

**Comment by Skyyblaze** [comment]
Thanks for the insight, alright will do!
